### ISSUE TITLE
Typo in the instructions

### ISSUE THREAD

**Issue by msamolis623** [binref/refinery-test-data#1]
![image](https://user-images.githubusercontent.com/60665953/173659987-2f7eda06-1340-4132-a1a4-1e3fe5122b76.png)

According to the documentation the AES command does not have a -M option only -m, --mode M. Changing the readme from -M to -m should resolve the typo and allow someone to correctly decrypt the test samples.

**Comment by jhhcs** [comment]
Thanks for reporting this! Should be fixed in a2d903a6bce65aec48e6a45d49f8767fab3b568f.
